FROM nginx:latest

# copy les fichiers du clone
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end

# copy le fichier config
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf
