services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    expose:
      - "5252"
    image: t6-back-end-image

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: t6-front-end-image
    expose:
      - "9000"
    depends_on:
      back-end:
        condition: service_started

  proxy-t6:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: t6-proxy-image
    ports:
      - "80:80"
    depends_on:
      back-end:
        condition: service_started
      front-end:
        condition: service_started
